/* SPDX-License-Identifier: ISC */

/**
 * @file ultrawidelock_ml.h — on-device classifiers, and the seam that keeps them replaceable.
 *
 * One classifier so far: line-of-sight vs obstructed, from the DW3000's own
 * receive diagnostics -- "is there a door between reader and phone", which the
 * distance alone cannot answer. A depth-2 decision tree: 776 B of flash for
 * everything here, 0 B of RAM, 28 B of stack, no interpreter, no allocation.
 * Generated by gen_model.py (tinyml repo); tests/host/test_ultrawidelock_ml.c certifies
 * the C classifies identically to the trained model.
 *
 * FEED IT THE RIGHT NUMBERS. ultrawidelock_ml_los_classify() takes raw features in
 * physical units, in enum ultrawidelock_ml_los_feature order, and a wrong array cannot be
 * detected -- every float is legal. Do not fill it by hand: use
 * ultrawidelock_ml_los_features() with the five CIA registers and the range.
 */
#ifndef ULTRAWIDELOCK_ML_H
#define ULTRAWIDELOCK_ML_H

#include <stdbool.h>
#include <stdint.h>

#include "ultrawidelock_ml_los_features.h"

#ifdef __cplusplus
extern "C" {
#endif

/** Channel condition between the reader and the phone. */
enum ultrawidelock_ml_los_class {
	/** Direct path present: the strongest arrival is the first arrival. */
	ULTRAWIDELOCK_ML_LOS_CLEAR = 0,
	/** Something is in the way; the first path is attenuated or late. */
	ULTRAWIDELOCK_ML_LOS_OBSTRUCTED = 1,
};

/**
 * HOW THE PHONE IS BEING CARRIED, which is the same channel question asked with
 * more resolution. CLEAR is exactly ULTRAWIDELOCK_ML_LOS_CLEAR; the other three are
 * exactly ULTRAWIDELOCK_ML_LOS_OBSTRUCTED, split by what is doing the obstructing.
 *
 * WHY SPLIT AT ALL. The binary class carries the SIGN of the obstruction effect,
 * which is all Result 21 left standing, and a widening spends only the sign. But
 * the magnitude that failed to replicate failed across BODIES, not across the
 * split below: a phone in a bag and a phone behind a hip are different amounts of
 * water and different antenna orientations, and nothing here has ever measured
 * whether they are different amounts of centimetre. docs/bodycal-falsification.md
 * is the protocol that would find out, and its pass condition is per-class
 * residual std <= ~15 cm. Until that capture exists these classes carry a
 * per-class POLICY number, never a measured constant.
 *
 * ORDER IS PART OF THE MODEL once a four-class tree is generated, exactly as the
 * feature order already is: the generator emits leaf indices, not names.
 */
enum ultrawidelock_ml_carry_class {
	/** Nothing in the way. Folds to ULTRAWIDELOCK_ML_LOS_CLEAR. */
	ULTRAWIDELOCK_ML_CARRY_CLEAR = 0,
	/** In the hand, body between hand and reader. Folds to OBSTRUCTED. */
	ULTRAWIDELOCK_ML_CARRY_HAND = 1,
	/** Trouser or jacket pocket. Folds to OBSTRUCTED. */
	ULTRAWIDELOCK_ML_CARRY_POCKET = 2,
	/** Bag, backpack or purse. Folds to OBSTRUCTED. */
	ULTRAWIDELOCK_ML_CARRY_BAG = 3,
};

/** How many there are. A table indexed by carry class is this long. */
#define ULTRAWIDELOCK_ML_CARRY_N_CLASSES 4

/**
 * Collapse a carry class onto the binary one every existing caller speaks.
 *
 * Total and exhaustive by construction: CLEAR is clear, everything else is
 * obstructed. This is the compatibility contract -- a caller that upgrades to
 * ultrawidelock_ml_los_carry_classify() and folds gets bit-identical behaviour to the
 * caller it replaced, which is what makes the upgrade reviewable.
 */
enum ultrawidelock_ml_los_class
ultrawidelock_ml_carry_to_los(enum ultrawidelock_ml_carry_class c);

/**
 * Classify the carry mode of one ranging exchange. The seam, and today a stub in
 * the only sense that matters: IT CANNOT YET RETURN POCKET OR BAG.
 *
 * WHAT SHIPS RIGHT NOW. The generated model in this tree is the two-class tree
 * documented at the top of this file, so this function classifies binary and
 * reports ULTRAWIDELOCK_ML_CARRY_HAND for every obstructed reception -- the least
 * specific obstructed class, chosen because a caller's per-class widening table
 * then reads the entry that says "some body is in the way" rather than one that
 * claims to know it is a rucksack. Callers MUST NOT read a HAND return as
 * evidence the phone is in a hand; it means obstructed, resolution unavailable.
 * ultrawidelock_ml_los_carry_trained() is how to ask which of the two you are getting,
 * and it is a compile-time constant, so a caller that branches on it costs
 * nothing in the build that does not have the model.
 *
 * THE SEAM ITSELF, and where the four-class model arrives from. gen_model.py in
 * the tinyml repo emits ultrawidelock_ml_los_tree.h; a four-class run emits
 * ultrawidelock_ml_carry_tree.h and ultrawidelock_ml_carry_scaler.h beside it, with
 * ultrawidelock_ml_carry_tree_predict() and ultrawidelock_ml_carry_{lo,scale}[] under the same
 * naming rule. ultrawidelock_ml_los.c picks that model up with __has_include and needs
 * no edit here, in CMakeLists.txt or in Kconfig to do it -- dropping the two
 * generated headers into src/ is the whole integration. That is deliberate: the
 * generated files stay generated, and this file stays the contract they satisfy.
 * Retraining needs captures this repo does not hold; see
 * docs/bodycal-falsification.md.
 *
 * @param feat  as for ultrawidelock_ml_los_classify(), same features, same order, same
 *              inability to detect a mis-ordered array.
 * @return enum ultrawidelock_ml_carry_class. Fold it with ultrawidelock_ml_carry_to_los() to
 *         get the binary answer; the fold is exact, not an approximation.
 *
 * Same cost class as ultrawidelock_ml_los_classify(): deterministic, reentrant,
 * allocation-free, no libc. A four-class depth-2 tree is still two comparisons.
 */
enum ultrawidelock_ml_carry_class
ultrawidelock_ml_los_carry_classify(const float feat[ULTRAWIDELOCK_ML_LOS_N_FEATURES]);

/**
 * True when a real four-class model is compiled in, false when the binary tree is
 * standing in for one. Constant for a given build; see the seam paragraph above.
 *
 * Ask it before believing a POCKET or BAG return, and before letting an installer
 * tune per-class widenings that a binary model can never distinguish.
 */
bool ultrawidelock_ml_los_carry_trained(void);

/**
 * Classify one ranging exchange from its receive diagnostics.
 *
 * @param feat  ULTRAWIDELOCK_ML_LOS_N_FEATURES values in physical units, indexed by
 *              enum ultrawidelock_ml_los_feature. Not checked and cannot be: every
 *              float is a legal feature value, so a mis-ordered array is
 *              indistinguishable from a real measurement.
 * @return enum ultrawidelock_ml_los_class.
 *
 * Deterministic, reentrant, allocation-free, and bounded at two comparisons
 * deep, so it is safe to call from the ranging path. It still should not be
 * called from the RX arm window: that has a ~1836 us deadline and this has no
 * business competing for it.
 */
enum ultrawidelock_ml_los_class
ultrawidelock_ml_los_classify(const float feat[ULTRAWIDELOCK_ML_LOS_N_FEATURES]);

/**
 * How much to trust the class ultrawidelock_ml_los_classify() just returned. Never a class.
 *
 * A single tree's leaf IS its class, so the generated predict_proba writes 1.0
 * and 0.0 and says nothing. This is the distance from a linear boundary fitted
 * on the same two features, and it was measured to grade the tree's answers.
 * Binned by quartile on 544 captures, out-of-fold, the tree is right:
 *
 *     lowest quartile   0.7721
 *                       0.8162
 *                       0.9338
 *     highest quartile  0.9853
 *
 * The obvious cheaper candidate does not work and was measured: per-leaf
 * training purity, which is what emlearn emits at leaf_bits=8 for no multiplies
 * at all, is NOT monotone (0.7890, 0.9389, 0.8514, 0.9103). See RESULTS.md
 * Result 16.
 *
 * @param feat  the same vector ultrawidelock_ml_los_classify() was given.
 * @return an unsigned confidence in dB-scaled units. Larger is more trustworthy.
 *         Zero means the reception sits on the boundary. There is no upper bound
 *         and no calibration to a probability; it is an ordering, so use it by
 *         comparing against a threshold chosen from the table above, never by
 *         reading it as a percentage.
 *
 * DELIBERATELY UNSIGNED, and this is the one thing to know before extending it.
 * The sign would be the linear model's own class, and that classifier is WORSE
 * than the tree: 0.8222 against 0.8773 on the same folds. Returning it would
 * hand every caller a five-point regression that looks like a free upgrade.
 * The two disagree on 9.7% of receptions, which would make a second unlabelled
 * drift monitor beside ultrawidelock_ml_los_disagrees(); exposing the sign for that is a
 * two-line change, and it should happen when something counts it, not before.
 *
 * Costs no RAM and no libc, like the rest of this module.
 */
float ultrawidelock_ml_los_confidence(const float feat[ULTRAWIDELOCK_ML_LOS_N_FEATURES]);

/**
 * The vendor rule of thumb, kept as the floor the model has to beat.
 *
 * Decawave APS006 says a first-path-to-total power difference above 6 dB implies
 * a non-line-of-sight channel. Refit on this board's own captures it scores
 * 0.7431 against the tree's 0.8800, so it is not a serious classifier -- it is a
 * reference. Two uses: it costs nothing to evaluate beside the tree, and the
 * RATE at which the two disagree is a drift signal that needs no ground truth.
 * A disagreement rate that moves means the install changed or the model went
 * stale, and that is the cheapest monitoring available for a shipped model.
 *
 * @param pwr_diff_db  rx_pwr - fp_pwr, in dB, as returned by
 *                     ultrawidelock_ml_los_features(). The model itself no longer carries
 *                     this column, which is why it is passed rather than read
 *                     out of the feature vector.
 */
enum ultrawidelock_ml_los_class ultrawidelock_ml_los_vendor(float pwr_diff_db);

/**
 * True when the two above disagree. See ultrawidelock_ml_los_vendor() for why to count it.
 *
 * @param pwr_diff_db  passed separately because the model no longer carries it:
 *                     rx_pwr - fp_pwr, both from the same dwt_rxdiag_t.
 */
bool ultrawidelock_ml_los_disagrees(const float feat[ULTRAWIDELOCK_ML_LOS_N_FEATURES],
				    float pwr_diff_db);

/**
 * Free-space spreading at a measured range, in dB, referenced to one metre.
 *
 * 20*log10(dist_cm / 100), computed from the integer's leading-bit position and a
 * nine-entry table rather than log10f, so this module keeps having no undefined
 * symbols at all. Maximum error against float64 is 0.183 dB over the range a
 * reader reports, and that error is dominated by range arriving as a whole number
 * of centimetres rather than by the table: see ultrawidelock_ml_range.c.
 *
 * @param dist_cm  ranging distance in centimetres, clamped to [10, 2000]. Below
 *                 10 the correction diverges and the reader really does report
 *                 0 cm; above 2000 the curve is flat enough not to matter.
 */
float ultrawidelock_ml_los_range_correction(uint16_t dist_cm);

/**
 * First-path power with the range taken out of it, which is the model's strongest
 * feature and the one at index ULTRAWIDELOCK_ML_LOS_F_FP_RESID.
 *
 * Equivalent to fp_pwr_db + ultrawidelock_ml_los_range_correction(dist_cm), and provided as
 * one call because the two are only meaningful together.
 *
 * THE RANGE MAY LAG. A DS-TWR round yields its distance when the round completes,
 * while the diagnostics are read per reception, so a caller classifying every
 * reception has the previous round's range. That is what the training data
 * measured too, since the captured range came from a status line printed every
 * ~2 s, so a lagged range is the case the numbers in RESULTS.md Result 11 are
 * about rather than an approximation of it.
 */
float ultrawidelock_ml_los_fp_resid(float fp_pwr_db, uint16_t dist_cm);

/**
 * Recover the true range from a reported one, given this reception's channel class.
 *
 * TWO MEASURED CONSTANTS, both from RESULTS.md Result 19, on this board in one
 * room:
 *
 *     true_cm ~= reported_cm + 25.5 - (obstructed ? 84.5 : 0)
 *
 * The 25.5 cm is the reader's own fixed shortfall. Nothing in this project has
 * ever programmed the DW3000 antenna-delay registers, so every range it reports
 * is uncalibrated in the absolute sense; two clear runs at 100 cm and 200 cm
 * measured -25.0 and -26.0 cm, agreeing to a centimetre across a doubling, which
 * is an offset rather than a scale error. The 84.5 cm is what a body in the path
 * adds, measured with the phone on a tripod so that only the subject moved.
 *
 * Fitted against all four runs the two constants predict 74.5/159.0/174.5/259.0
 * against measured 75/155/174/263: worst error 4 cm over a 2:1 range span.
 *
 * WHY THIS ONLY EVER ADDS PERMISSION, which is the property that makes it safe to
 * apply to a lock. Obstruction inflates range and never shrinks it, so undoing it
 * cannot manufacture proximity the radio did not see. The check that defends
 * against a deliberate distance-reduction attack is STS quality, and nothing
 * here touches it.
 *
 * FEED IT A FILTERED RANGE, NOT ONE RECEPTION. The obstructed captures had
 * interquartile spreads of 38 and 47.5 cm against 7 and 11.5 for clear, so a
 * single obstructed reception is a poor estimate of anything and this correction
 * does not make it a better one. ultrawidelock_approach already takes a median over its
 * window; that is the quantity to correct.
 *
 * @param reported_cm  the range as the reader produced it.
 * @param c            the class ultrawidelock_ml_los_classify() returned for the reception
 *                     the range came from. Pass ULTRAWIDELOCK_ML_LOS_CLEAR to apply the
 *                     antenna offset alone.
 * @return the corrected range in centimetres, clamped at 0. An obstructed
 *         reception at very short range can correct below zero, and that is a
 *         reading the correction had no business being applied to rather than a
 *         negative distance.
 *
 * ONE ROOM, ONE PHONE, ONE SUBJECT, ONE SESSION, and a body is not a door. The
 * 25.5 cm in particular is this board and this antenna rather than a family
 * constant, and antenna delay drifts with temperature in ways nothing here
 * measured.
 */
uint16_t ultrawidelock_ml_los_range_true_cm(uint16_t reported_cm,
					    enum ultrawidelock_ml_los_class c);

/**
 * The Ipatov CIA diagnostics the features are computed from, as read.
 *
 * A struct rather than five uint32_t parameters precisely because they are five
 * same-typed integers: positional arguments there are a silent mis-order waiting
 * to happen, and like the feature vector itself a mis-ordered read produces a
 * confident wrong class rather than an error. Field for field from
 * dwt_rxdiag_t, so a caller writes .f1 = d.ipatovF1 and can check it by eye.
 *
 * ultrawidelock_ml deliberately does not include deca_device_api.h. That header is
 * LicenseRef-QORVO-2 and is only present on targets that carry the driver, while
 * this module is built and tested on the host with no driver at all.
 */
struct ultrawidelock_ml_cia {
	uint32_t f1;           /**< dwt_rxdiag_t::ipatovF1 */
	uint32_t f2;           /**< dwt_rxdiag_t::ipatovF2 */
	uint32_t f3;           /**< dwt_rxdiag_t::ipatovF3 */
	uint16_t accum_count;  /**< dwt_rxdiag_t::ipatovAccumCount */
	uint32_t channel_area; /**< dwt_rxdiag_t::ipatovPower, a 2^17-scaled area */
	/**
	 * Amplitude of the strongest CIR sample: dwt_rxdiag_t::ipatovPeak masked
	 * to IP_DIAG_0_PEAKAMP, bits [20:0]. The AMPLITUDE ALONE, not the packed
	 * register — the index half is a sample position and this module has no
	 * use for one, so taking the register whole would only invite a caller to
	 * pass it unmasked and get a ratio 2^21 too large that still looks like a
	 * dB number.
	 *
	 * Read ONLY by ultrawidelock_ml_los_diag(). The shipped model does not use
	 * it and ultrawidelock_ml_los_features() does not look at it, so leaving it
	 * zero keeps the classifier's answers unchanged.
	 */
	uint32_t peak_amp;
};

/**
 * Training columns that are NOT model inputs, from one reception's registers.
 *
 * SEPARATE FROM THE FEATURE VECTOR ON PURPOSE. enum ultrawidelock_ml_los_feature is
 * generated by gen_model.py and its length is part of the fitted model; adding a
 * column there would mean the C fills a vector the trained tree never saw.
 * Everything here is a candidate for a FUTURE fit, computed on-device only so a
 * capture run records it beside the reception it came from. Nothing in the
 * unlock path reads any of it.
 *
 * NO NOISE FLOOR, and this is the field a reader will look for. The DW3000's
 * dwt_rxdiag_t has no noise members at all: maxNoise and stdNoise are DW1000
 * fields (RX_FQUAL), and the DW3000 CIA bank exposes IP_DIAG_0..12 of which only
 * PEAKLOC/PEAKAMP, the channel area, F1..F3, FPLOC and NACC are named in the
 * vendor register header this repo carries. IP_DIAG_5/6/7/9/10/11 exist with no
 * documented subfields, so nothing here can say whether any of them is a noise
 * estimate, and inventing one would produce a confident column of nonsense
 * rather than an error. The capture emits the raw peak, F1..F3, channel area and
 * accumulator count instead, so a noise column can be DERIVED offline once its
 * source is established.
 */
struct ultrawidelock_ml_diag {
	/** 10*log10(F1^2+F2^2+F3^2 / C^2) - A, in dB. The first path's own power. */
	float fp_pwr_db;
	/** 10*log10(area*2^17 / C^2) - A, in dB. The whole channel's power. */
	float rx_pwr_db;
	/**
	 * rx_pwr - fp_pwr, in dB. Identical to the pwr_diff_db that
	 * ultrawidelock_ml_los_features() hands out, and it is here so a capture can
	 * record the column without also running the classifier.
	 */
	float delta_p_db;
	/**
	 * 10*log10((F1^2+F2^2+F3^2) / peak_amp^2), in dB. How far the first path
	 * sits below the strongest arrival.
	 *
	 * A RATIO, NOT A POWER, which is why A does not appear in it: A is a
	 * constant offset on both halves and cancels, and so does the accumulator
	 * count. Both halves are CIR magnitudes off the same Ipatov accumulator in
	 * the same units, so the quotient is dimensionless.
	 *
	 * SIGN IS THE POINT. The peak is by construction the largest sample, so
	 * with the first path AT the peak this sits just above 0 dB (the numerator
	 * sums three taps against the peak's one, so a clean channel can reach
	 * about +4.8 dB), and it falls the further the first arrival is below the
	 * strongest one -- which is what an obstruction does. UNFITTED: no
	 * threshold on this has been trained or measured on this board.
	 */
	float fp_peak_db;
};

/**
 * Fill a feature vector from one reception's diagnostics and the current range.
 *
 * @param cia          the Ipatov registers, as read.
 * @param dist_cm      ranging distance in centimetres. May lag by one round; see
 *                     ultrawidelock_ml_los_fp_resid() for why that is the trained case
 *                     rather than an approximation of it.
 * @param feat         filled on success, ready for ultrawidelock_ml_los_classify().
 * @param pwr_diff_db  rx_pwr - fp_pwr, for ultrawidelock_ml_los_vendor() and the
 *                     disagreement counter. NULL if not wanted.
 * @return false when the CIA read failed, in which case nothing is written and
 *         the reception must be DROPPED rather than classified. A zeroed
 *         accumulator count or channel area is a failed read, not a very weak
 *         channel, and the training data drops those receptions too.
 *
 * Allocation-free and reentrant, like everything else here. Costs one 64-bit
 * multiply-accumulate and three logarithms.
 */
bool ultrawidelock_ml_los_features(const struct ultrawidelock_ml_cia *cia, uint16_t dist_cm,
			 float feat[ULTRAWIDELOCK_ML_LOS_N_FEATURES], float *pwr_diff_db);

/**
 * Fill the training columns of struct ultrawidelock_ml_diag from the same registers.
 *
 * For a CAPTURE RUN, not for a decision. Nothing the shipped classifier does
 * calls this, and adding a call to it cannot change what
 * ultrawidelock_ml_los_classify() answers -- the two share the arithmetic that
 * produces fp_pwr and rx_pwr but this one writes only to its own struct.
 *
 * @param cia  the Ipatov registers, as read. peak_amp must be the AMPLITUDE half
 *             of ipatovPeak (bits [20:0]); see struct ultrawidelock_ml_cia.
 * @param out  filled only on success.
 * @return false on a failed CIA read, by exactly the rule
 *         ultrawidelock_ml_los_features() uses -- a zero accumulator count, channel
 *         area or first-path sum -- plus a zero peak amplitude, which is a
 *         failed read for the same reason: the peak is by construction the
 *         largest sample in the CIR, so a channel that produced any F1..F3 at
 *         all cannot have a zero peak. Nothing is written when it returns false,
 *         so a caller cannot mistake a stale struct for a fresh reading.
 *
 * Allocation-free, reentrant, no libc, task context: four logarithms, like the
 * rest of this module.
 */
bool ultrawidelock_ml_los_diag(const struct ultrawidelock_ml_cia *cia,
			       struct ultrawidelock_ml_diag *out);

#ifdef __cplusplus
}
#endif

#endif /* ULTRAWIDELOCK_ML_H */
